#!/bin/bash

for file in "$@"
do
  if [ -f $file ]
  then
    # Counting number of rows
    rows=$(grep -v '^#' $file | wc -l | cut -f1 -d' ')
    
    # Printing number of columns for every row
    grep -v '^#' $file | awk '{print NF}' > tmp
    
    # Checking integrity
    check=$(sort -u tmp | wc -l | cut -f1 -d' ')
    if [ $check -eq 1 ]
    then
      # Counting columns
      cols=$(head -n1 tmp)
    
      # Inquiring the user about the desired column
      read -p 'Select the column to average :: ' avecol
    
      echo "grep -v '^#' $file | binaver -r $rows -c $cols -k $avecol"
    fi

    rm tmp
  fi
done
